//
//  WeaponList.swift
//  DS3
//
//  Created by Tom Clifford on 06/04/2021.
//

import Foundation
import struct SwiftUI.PreviewDevice

class WeaponList
{
    var allWeapons: [Weapon] { weaponsCache }

    /// An in memory cache of weapons  that are persistently stored
        private var weaponsCache: [Weapon] = [
            .init(name: "None", description: "None", location: "None", weight: 0.0, durability: 0, imageKey: "wpn_none", physAtk: 0, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 0, physDef: 0, magDef: 0, fireDef: 0, lightningDef: 0, darkDef: 0, stability: 0, bleed: 0, poison: 0, frost: 0, dmgType: [], ability: Skill(name: "Parry", description: "Parrys the foes attack"), fpCost: 0, strReq: 0, strScale: Weapon.Scaling.None.rawValue, dexReq: 0, dexScale: Weapon.Scaling.None.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: "None"),
            .init(name: "Fume Ultra Greatsword", description: "This twisted sword, the heaviest of all ultra greatswords, resembles black slate.\nThis weapon, said to belong to a traitor from long ago, was so heavy that it found no owner, and became a forgotten relic of history.", location: "Dropped by Knight Slayer Tsorig underneath the Smoldering Lake.  He can be found beyond the areas with the rats and the basilisks, but before the exit that goes up to the ballista.", weight: 25.5, durability: 170, imageKey: "wpn_fume_ultra_greatsword", physAtk: 149, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 80, magDef: 55, fireDef: 65, lightningDef: 60, darkDef: 65, stability: 55, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Strike.rawValue], ability: Skill(name: "Stomp", description: "Use one's weight to lunge forward with a low stance and increased poise, and follow with a crushing strong attack."), fpCost: 10, strReq: 50, strScale: Weapon.Scaling.A.rawValue, dexReq: 10, dexScale: Weapon.Scaling.E.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.UltraGreatsword.rawValue),
            .init(name: "Dagger", description: "Standard small dagger.\nSmall daggers lack power or reach, but can deal quick consecutive hits due to their light weight. Highly effective when used for critical hits, such as after parrying or attacking from behind.", location: "Buy for 300 souls from Shrine Handmaid.", weight: 1.5, durability: 50, imageKey: "wpn_dagger", physAtk: 65, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 130, physDef: 35, magDef: 20, fireDef: 15, lightningDef: 15, darkDef: 20, stability: 15, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Slash.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Quickstep", description: "Instantly step behind or around the side of foes. Especially effective when locked on to target."), fpCost: 5, strReq: 5, strScale: Weapon.Scaling.E.rawValue, dexReq: 14, dexScale: Weapon.Scaling.C.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Dagger.rawValue),
            .init(name: "Grass Crest Shield", description: "Old medium metal shield of unknown origin.\nThe grass crest is lightly imbued with magic, which slightly speeds stamina recovery", location: "Road of Sacrifices: From the Crucifixion Woods bonfire, drop down to the right of the large crab towards one of the large trees. Loot the corpse on the right side of the tree.", weight: 4.5, durability: 75, imageKey: "wpn_grass_crest_shield", physAtk: 92, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 89, magDef: 43, fireDef: 38, lightningDef: 38, darkDef: 36, stability: 50, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Strike.rawValue], ability: Skill(name: "Parry", description: "Repel an attack at the right time to follow up with a critical hit.\nWorks when equipped in either hand"), fpCost: 0, strReq: 10, strScale: Weapon.Scaling.D.rawValue, dexReq: 0, dexScale: Weapon.Scaling.None.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Shield.rawValue),
            .init(name: "Black Blade", description: "A short katana wielded by the swordsman and distinguished guest of High Lord Wolnir. This shiny black blade is thick, but shorter than the typical katana.\nThe swordsman was a master of a rare technique, traces of which can be observed in this weapon's strong attack.", location: "Looted from a Mimic chest near the Flame Demon, on the way to Smouldering Lake.", weight: 6.5, durability: 50, imageKey: "wpn_black_blade", physAtk: 122, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 50, magDef: 30, fireDef: 25, lightningDef: 25, darkDef: 30, stability: 35, bleed: 30, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Slash.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Hold", description: "Assume a holding stance to rapidly execute a lunging slash with a normal attack, or a deflecting parry with a strong attack."), fpCost: 0, strReq: 18, strScale: Weapon.Scaling.E.rawValue, dexReq: 18, dexScale: Weapon.Scaling.C.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Katana.rawValue),
            .init(name: "Parrying Dagger", description: "Dagger with a greatly curved guard.\nA dagger made especially for parrying which is usually equipped in one's left hand in place of a shield.", location: "Sold by Unbreakable Patches for 2000 souls.", weight: 1.0, durability: 40, imageKey: "wpn_parrying_dagger", physAtk: 30, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 110, physDef: 30, magDef: 20, fireDef: 15, lightningDef: 15, darkDef: 20, stability: 15, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Slash.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Parry", description: "Repel an attack at the right time to follow up with a critical hit. Works while equipped in either hand."), fpCost: 0, strReq: 5, strScale: Weapon.Scaling.E.rawValue, dexReq: 14, dexScale: Weapon.Scaling.C.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Dagger.rawValue),
            .init(name: "Harpe", description: "The large sickle-shaped body, used for severing corpses, is a worker’s tool in the Undead Settlement.\nThe sharp edge is on the inside of the weapon, itself designed for cutting and pulling, thus allowing for good damage against shielded foes.", location: "Dropped by Red Eyed Peasant Hollow at Undead Settlement (most easily farmed from the Dilapidated Bridge bonfire, either by backtracking all the way up the stairs past the Evangelist, or inside the shack past the white birch tree).", weight: 1.5, durability: 45, imageKey: "wpn_harpe", physAtk: 35, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 0, physDef: 35, magDef: 20, fireDef: 15, lightningDef: 15, darkDef: 20, stability: 15, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Slash.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Quickstep", description: "Instantly step behind or around the side of foes. Especially effective when locked on to target."), fpCost: 5, strReq: 8, strScale: Weapon.Scaling.E.rawValue, dexReq: 10, dexScale: Weapon.Scaling.C.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Dagger.rawValue),
            .init(name: "Shortsword", description: "Small straight sword excelling in thrusting attacks.\nThe shortsword is a light and easily wielded straight sword, due to its minimal attribute requirements.", location: "Sold by Shrine Handmaid.in Firelink Shrine for 600 souls", weight: 2.0, durability: 65, imageKey: "wpn_shortsword", physAtk: 45, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 110, physDef: 45, magDef: 30, fireDef: 25, lightningDef: 25, darkDef: 30, stability: 30, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Stance", description: "While in stance, use normal attack to break a foe's guard from below, and strong attack to slash upwards with a forward lunge."), fpCost: 18, strReq: 8, strScale: Weapon.Scaling.D.rawValue, dexReq: 10, dexScale: Weapon.Scaling.C.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.StraightSword.rawValue),
            .init(name: "Dark Sword", description: "Pitch-black straight sword of the Darkwraith, survivor of the land swallowed by darkness.\nThe Darkwraiths were the first red orb invaders, and originators of a unique sword technique inspired by their thick, broad blades.", location: "Dropped by Darkwraiths in High Wall of Lothric (tower on the wall bonfire) and Farron Keep located just before Abyss Watchers boss fight.", weight: 4.5, durability: 80, imageKey: "wpn_dark_sword", physAtk: 55, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 55, magDef: 35, fireDef: 30, lightningDef: 30, darkDef: 35, stability: 35, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Stomp", description: "Use one's weight to lunge forward with a low stance and increased poise, and follow with strong attack for an upward slash."), fpCost: 13, strReq: 16, strScale: Weapon.Scaling.C.rawValue, dexReq: 15, dexScale: Weapon.Scaling.D.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.StraightSword.rawValue),
            .init(name: "Gotthard Twinswords", description: "The hunters known as the King's Black Hands wielded paired weapons. These belonged to Gotthard, who fled the castle.\nGotthard rose quickly through the knighthood, no surprise to those who have witnessed his swordsmanship.", location: "Can be found on Black Hand Gotthard's corpse just outside the Grand Archives. You must have defeated Aldrich, Yhorm, and the Abyss Watchers or this sword will not be there.", weight: 6.5, durability: 70, imageKey: "wpn_gotthard_twinswords", physAtk: 50, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 50, magDef: 30, fireDef: 25, lightningDef: 25, darkDef: 30, stability: 30, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue, Weapon.DamageType.Thrust.rawValue], ability: Skill(name: "Spin Slash", description: "Slice into foes with a large spinning motion, and use strong attack to lengthen attack and end with a double-bladed thrust."), fpCost: 5, strReq: 12, strScale: Weapon.Scaling.D.rawValue, dexReq: 18, dexScale: Weapon.Scaling.D.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.StraightSword.rawValue),
            .init(name: "Bastard Sword ", description: "A widely-used heavy greatsword normally wielded with two hands.\nBroad horizontal sweeping attacks make this sword effective against multiple enemies, but unwieldy in narrow spaces.", location: "urchased from Greirat of the Undead Settlement after he arrives at Firelink Shrine or from Shrine Handmaid after giving her his ashes for 3,000 souls.", weight: 8.0, durability: 75, imageKey: "wpn_bastard_sword", physAtk: 50, magAtk: 0, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 50, magDef: 35, fireDef: 30, lightningDef: 30, darkDef: 35, stability: 35, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue], ability: Skill(name: "Stomp", description: "Use one's weight to lunge forward with a low stance and increased poise, and follow with a strong attack for an upward slash."), fpCost: 12, strReq: 16, strScale: Weapon.Scaling.D.rawValue, dexReq: 10, dexScale: Weapon.Scaling.D.rawValue, intReq: 0, intScale: Weapon.Scaling.None.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Greatsword.rawValue),
            .init(name: "Greatsword of Judgment", description: "ceremonial sword, held in Pontiff Sulyvahn's left hand, respresenting the judgement of the moon, but with magic far closer to sorcery than any existing lunar power. Its dark blue hues, deeper than the darkest moon, reflect sorcerer Sulyvahn's true nature.", location: "Transposed with the Soul of Pontiff Sulyvahn.", weight: 9.0, durability: 85, imageKey: "wpn_greatsword_of_judgement", physAtk: 50, magAtk: 86, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 50, magDef: 35, fireDef: 30, lightningDef: 30, darkDef: 35, stability: 40, bleed: 100, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue], ability: Skill(name: "Stance of Judgement", description: "Assume stance to unleash dark magic. Use normal attack for a lunging thrust, and strong attack to emit side-sweeping wave."), fpCost: 20, strReq: 17, strScale: Weapon.Scaling.D.rawValue, dexReq: 15, dexScale: Weapon.Scaling.D.rawValue, intReq: 12, intScale: Weapon.Scaling.D.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Greatsword.rawValue),
            .init(name: "Moonlight Greatsword", description: "Legendary dragon weapon associated with Seath the paledrake.\nCharge strong attack to its limit to unleash moonlight wave.\nOceiros, the Consumed King, was infatuated with the search for moonlight, but in the end, it never revealed itself to him.", location: "Crafted via Soul Transposition from the Soul of Consumed Oceiros.", weight: 10.5, durability: 75, imageKey: "wpn_moonlight_greatsword", physAtk: 55, magAtk: 130, fireAtk: 0, lightningAtk: 0, darkAtk: 0, critical: 100, physDef: 55, magDef: 60, fireDef: 35, lightningDef: 35, darkDef: 40, stability: 40, bleed: 0, poison: 0, frost: 0, dmgType: [Weapon.DamageType.Standard.rawValue], ability: Skill(name: "Moonlight Vortex", description: "Draw sword back and thrust to unleash torrential moonlight."), fpCost: 18, strReq: 16, strScale: Weapon.Scaling.E.rawValue, dexReq: 11, dexScale: Weapon.Scaling.None.rawValue, intReq: 26, intScale: Weapon.Scaling.C.rawValue, fthReq: 0, fthScale: Weapon.Scaling.None.rawValue, weaponType: Weapon.WeaponTypes.Greatsword.rawValue)

    
        ]
}
